### ISSUE TITLE
Advice on Github Pull Request Workflow and CI/CD

### ISSUE THREAD

**Issue by JessicaSachs** [mateodelnorte/meta#187]
## Sequencing Pull Requests and managing CI/CD

Hi! First off, thank you so much for making such a great tool. I can't find anything similar to meta online. It's a great idea.

#### Our usecase

1. I have a main repository that will get deployed. It depends on some sub-packages.
2. I make changes to [A, B, C] that all depend on each other.
3. The changes are tightly coupled and I cannot deploy any of them separately.
4. I want to ensure that B and C perform integration tests against the shared branch and do not break A.
5. After everything is tested, I want to submit pull requests for [A, B, C] and merge them in for the final binary/build

#### Super simple pic

```
   A      | - A is the main project (meta)
 /   \    | -   
B     C   | - [B, C] are subdeps
```

#### What we need clarity on
We're a little confused how the sequencing of merging PRs works. I'd love some guidance or literature on how you suggest managing the PR workflow and structuring a CI/CD pipeline.
1. It's _possible_ to merge [B, C] _without_ merging A.
2. Doing this would put A out-of-sync.
3. At best, A is untested against the newer versions of B or C.
4. At worst, the newer versions of B or C are not backwards compatible against A.

#### All that said....
_I really want to use meta, and my team really wants to use meta._ I can't find any documentation on how to integrate meta into CI/CD or a functional github workflow, and the gittr link to your chat seems to be broken. ☹️ I'm around on Discord if you'd like to connect in a more realtime fashion, but also reachable via Github.

**Comment by mateodelnorte** [comment]
Hi @JessicaSachs! Thanks for the extremely clearly written issue. And thanks for the interest in meta. 

This seems like one of those "it depends" responses for a question that could pop up in a number of scenarios in engineering. The above is a good example if talking about a library that consists of many child libraries. It's also a good example of a distributed system or large application made of many subsystems. 

Your answer is either going to be "versioning", "convention around deployments", or both. 

We can use the example of `meta`, itself, as the library example. We use greenkeeper to watch for version bumps on any dependency, for meta itself and for any of the child modules. When we make an update to `meta-git`, for example, we publish and greenkeeper catches this. `meta` will not break because we can match versioning info in package.json to ensure things march in lock step. 

You can do similar configuration of a distributed system with versioning as well, having versioned API endpoints within your single api. Or, you can have multiple instances of services running at different versions simultaneously with requests being routed to those instances by reverse proxy, according to versioning on inbound URLs, or some other rules. 

Or, you can put up a maintenance page and swap out the instances in controlled downtime. 

One thing that I will point out, however, is that you're noting A will get out of sync with B and C. If what you're building is a distributed system, of microservices, for example, it's generally best practice to have A strictly be a meta repo. It contains information about your other repos, and perhaps support tooling (a Makefile, docker-compose files, common support scripts for your system, etc). 

Can you tell me a bit more about what kinda of software system A, B, and C comprise in your case?

**Comment by mateodelnorte** [comment]
BTW, I just clicked on the gitter link and it's working fine. 😄

**Comment by JessicaSachs** [comment]
We're building static, client-side assets.
* A is our main website. A is the only thing that gets deployed on its own.
* B would be an i18n-strings library.

We want A to depend on B for local development. For B, we often make dependent changes, where B really needs to be merged at the same time as A.

Looking at the `meta gh` or `meta git` executables, I see that the creation of PRs and branches across repositories is easy and automated, so my question lies mostly around "OK, so you've made all these branches and PRs... is there any advice around a good workflow to manage merging them?"

Also gittr still isn't working for me (gittr.im/meta)

<img width="1341" alt="Screen Shot 2019-08-19 at 11 32 39 AM" src="https://user-images.githubusercontent.com/2801156/63278401-2dfc9180-c275-11e9-92ea-e3f0d2fd08af.png">

**Comment by mateodelnorte** [comment]
Is that the link the `chat on gitter` button is leading you to? It should
be this, and is when I view it:

[image: image.png]

https://gitter.im/meta-repos-ftw/Lobby

**Comment by mateodelnorte** [comment]
Gotcha. Yes.  

Here's how I typically develop: 

1. start a new feature
2. `meta git checkout feat/my-new-feature` in the meta repo
3. develop across multiple branches
4. `meta git add .`
5. `meta git status` to track my changes
6a. for simple changes `meta git commit -m "some message that works for everything"`
6b. `cd` into relevant repos with changes and `git commit -m "some message"`
7. `meta git push origin feat/my-new-feature`
8. `meta gh -pr [options for pr]`. 

The above will end up allowing me to create a pr only for the branches for which I pushed changes to a new branch. Git will ignore pushing on any branches with no changes. Github will ignore creating a PR if there is no branch. 

Note, `meta gh` is a tiny bit flakey. If you want get your options to work correctly, you can drop back to `meta exec "gh [... options]" or `loop "gh [... options]"`. 

After all this, merge, in the order you like. 

Is that the type of process you're looking for?

**Comment by JessicaSachs** [comment]
Thank you! Finally had the chance to look at this (Got everything working in Teamcity, etc 💯)
Super excited to roll this out!!
