### ISSUE TITLE
meta commands are also run on the meta repository itself.

### ISSUE THREAD

**Issue by manno** [mateodelnorte/meta#232]
## 🐛 Bug Report

meta commands are also run on the meta repository itself.

## To Reproduce

I'm using https://github.com/manno/quarks-meta
When I run `meta git status` I see that 'git status' is executed on the meta repo itself.

## Expected behavior

The documentation says meta will run the command "in each directory listed in projects of the .meta JSON configuration file".
However the meta repo is not listed in that sections.

**Comment by patrickleet** [comment]
hm, not really sure it's a bug as it's always worked this way - perhaps the wording could be fixed though.

there are flags you can use to exclude a directory

For example, if the name of the meta directory is "meta"

```
meta git status --exclude=meta
```

**Comment by patrickleet** [comment]
@mateodelnorte and I often have `Makefile`s in our projects and do something like this:

```
NODE_APPS=app1,service1,app2,service2

install:
	meta npm install --include-only $(NODE_APPS)
```

**Comment by patrickleet** [comment]
meta inherits this functionality from `loop`, fyi

https://www.npmjs.com/package/loop

**Comment by mateodelnorte** [comment]
@manno the excerpt you quoted is under the docs section for how to develop on `meta` locally. That's not a description of how `meta` works. That sentence is valid because the package.json script specifically provides an `--exclude meta` option. Though, the script was renamed from `install` to `install-meta`, so we should update that in the readme: https://github.com/mateodelnorte/meta/blob/master/package.json#L18

**Comment by manno** [comment]
Ah, right. I didn't understand from the text and screenshots that the meta repo itself will be included and tried to find something in the text. It wasn't listed in the JSON file.

This is not a bug then, thanks for explaining the loop options.
