### ISSUE TITLE
Please provide an integration with automated build servers?

### ISSUE THREAD

**Issue by constructs** [mateodelnorte/meta#40]
Feature request:
Hello,
As a user, I would like to please have a way to automate nightly builds for the source depending on meta tool so that 
1. I dont have to create seperate scripts that do the checkout of my code using meta
2. The build system knows when to checkout based on the changes done in code
3. The tags are applied to the specific repositories on successful completion of a build and test.

**Comment by mateodelnorte** [comment]
So, some of the terminology you're using doesn't really make sense in the world of `git`. `meta-git` can already do a `git checkout` on a specific branch of many projects at once. But I'm guessing what you mean is to do a `git clone` of many projects at once – which it can also already do. 

Everything you've mentioned above is quite possible, but is not possible to bake into `meta` because the steps have to be scripted in using your continuous integration tool of choice, be it travis, jenkins, etc. 

Here's the setup my company currently has: 

- all code is housed in repositories under a github organization
- we have a docker swarm set up on ec2 with the docker-jenkins plugin and jenkins deployed within the swarm
- the docker-jenkins plugin is set to watch all repositories for code pushes
- it jenkins will automatically run a build for any repo that has a new push, where that repo contains a Jenkinsfile
- each repository's Jenkinsfile defines the appropriate steps to build, test, release, and deploy that project directly into our cloud

You can imagine it doesn't make sense to build that into meta because meta has no idea what your project's build, release, or deploy steps should be. 

Your meta repo is just a collection of other repos. Each of them should have tests. Each of them should build and deploy. You can also have tests in your meta repo. If you do, I would recommend these be integration tests. You can also put these integration tests into their own child repo, within the meta repo.

**Comment by constructs** [comment]
Thanks a lot for the information.
I have updated the question to fix the terminology. I guess I still somehow have traces of clearcase left in me.
Anyways, my problem is that the two repositories are intertwined, in the sense that they need to be compiled together to create a single binary (c++, no library, all into 1 binary, to avoid abi problems)

In this case, I guess, I need a jenkins plugin so that jenkins can show me what changed in which repo, when it clones/pulls code and builds?

Please correct if I am wrong..

**Comment by mateodelnorte** [comment]
Perhaps what you want is something similar to https://greenkeeper.io, where an updated release of a dependency can lead to the release of the project that uses that dependency. 

You could structure your builds such that a build of the parent repo is triggered after a successful automatic build of the child project. Pretty much every build system [allows that](https://www.google.com/search?rlz=1C5CHFA_enUS786US786&ei=j6kWW-DUG4Tz5gKLnruQDQ&q=api+trigger+build&oq=api+trigger+build&gs_l=psy-ab.3..0i71k1l8.2273.2273.0.2324.1.1.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..1.0.0....0.s4afhCPxxyU). Then, in your meta repo, you would just be sure to do a pre-build step of `meta git update` which will populate your child repos. You can then perform your full build.
